# Generated by Django 2.2.6 on 2020-01-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Bangalore', max_length=256),
        ),
    ]
